---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: Ensure C# REPL tool is installed using dotnet
  ansible.builtin.shell: |
    if ! dotnet tool list -g | grep -q 'csharprepl'; then
      dotnet tool install -g csharprepl
    fi
  become: true
  environment:
    PATH: "{{ ansible_env.HOME }}/.dotnet/tools:{{ ansible_env.PATH }}"
  register: install_result
  changed_when: install_result.rc == 0
