---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: Install C# REPL tool using dotnet
  ansible.builtin.command:
    cmd: "dotnet tool install -g csharprepl"
  become: true
  environment:
    PATH: "{{ ansible_env.HOME }}/.dotnet/tools:{{ ansible_env.PATH }}"
  changed_when: "'csharprepl' not in lookup('pipe', 'dotnet tool list -g')"
