---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: Launch Firefox (so it creates it required directories)
  ansible.builtin.command: firefox &
  async: 1
  poll: 0

- name: Wait for 10 seconds
  ansible.builtin.pause:
    seconds: 10

- name: Quit Firefox after 10 seconds
  ansible.builtin.command: pkill firefox

- name: Restoring Firefox Bookmarks
  block:
    - name: Find Firefox profile directory
      find:
        paths: "{{ lookup('env', 'HOME') }}/.mozilla/firefox/"
        patterns: "*.default-release"
        file_type: directory
      register: firefox_profile_dir

    - name: Copy places.sqlite file to Firefox profile
      copy:
        src: places.sqlite
        dest: "{{ firefox_profile_dir.files[0].path }}/places.sqlite"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0644"
      when: firefox_profile_dir.matched > 0
