- hosts: localhost
  vars:
    XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
  tasks:
  - name: Create config directory
    file:
      path: "{{XDG_CONFIG_HOME}}"
      state: directory
  - name: "Get 'password' from Bitwarden record with ID 'bafba515-af11-47e6-abe3-af1200cd18b2'"
    ansible.builtin.debug:
      msg: >-
        {{ lookup('community.general.bitwarden', 'b65c4ea0-f908-497f-9a9e-aec200956fd6', search='id', field='password') | first }}
  roles:
    # - system-upgrade
    # - ssh
    # - wallpaper
    # - fonts
    # - flatpak

    # Packages from source
    # - yay
    # - jetbrains-toolbox
    # - bitwarden-cli
    
    # Regular (or Flatpak) Packages
    # - authenticator
    # - oathtool
    # - azure-storage-explorer
    # - blueman
    # - btop
    # - build-tools
    # - calibre
    # - copyq
    # - discord
    # - firefox
    # - fish
    # - fzf
    # - git
    # - httpie
    # - insomnium
    # - jq
    # - libreoffice
    # - localsend
    # - mpv
    # - neofetch
    # - nvm
    # - oathtool
    # - obsidian
    # - redshift
    # - signal
    # - teamviewer
    # - todoist
    # - vscodium
    # - zed
    # - zoxide
    

