- hosts: localhost
  vars:
    XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
  tasks:
  - name: Create config directory
    file:
      path: "{{XDG_CONFIG_HOME}}"
      state: directory
  roles:
    # - system-upgrade
    # - ssh
    # - wallpaper
    # - fonts
    # - flatpak

    # Packages from source
    # - yay
    # - jetbrains-toolbox
    # - bitwarden-cli
    
    # Regular (or Flatpak) Packages
    # - authenticator
    # - oathtool
    # - azure-storage-explorer
    # - blueman
    # - btop
    # - build-tools
    # - calibre
    # - chromium
    # - copyq
    # - discord
    # - docker
    # - dotnet
    # - firefox
    # - fish
    # - foot
    # - fzf
    # - git
    # - grim
    # - httpie
    # - insomnium
    # - jq
    # - libreoffice
    # - localsend
    # - mpv
    # - neo4j-desktop
    # - neofetch
    # - oathtool
    # - obsidian
    # - redshift
    # - ripgrep
    # - signal
    # - slurp
    # - teamviewer
    # - todoist
    # - vscodium
    # - waybar
    # - wezterm
    # - wl-copy
    # - zed
    # - zoxide
    

