- hosts: localhost
  vars:
    XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
  tasks:
    - name: Create config directory
      file:
        path: "{{XDG_CONFIG_HOME}}"
        state: directory
  roles:
    - system-upgrade
    - ssh
    - wallpaper
    - fonts
    - flatpak

    # Packages from source
    - yay
    - jetbrains-toolbox
    - bitwarden-cli

    # Regular (or Flatpak) Packages
    - adb
    - authenticator
    - azure-storage-explorer
    - blueman
    - btop
    - build-tools
    - calibre
    - chromium
    - copyq
    - discord
    - docker
    - dotnet
    - firefox
    - fish
    # - foot
    - fzf
    - git
    - gnome-keyring
    - grim
    - httpie
    - hyprland
    # - i3
    # - i3status
    - insomnium
    - jq
    - libreoffice
    - localsend
    - mpv
    - neo4j-desktop
    - neofetch
    - nvim
    - oathtool
    - obsidian
    - redshift
    - ripgrep
    - rofi
    - signal
    - slurp
    - starship
    # - sway
    - teamviewer
    - todoist
    - vscodium
    - waybar
    - wezterm
    - wl-clipboard
    - zed
    - zoxide
