- hosts: localhost
  become: true
  vars:
    wallpaper_uri: "./files/wallpaper.jpg"
  tasks:
    - include_tasks: tasks/system-upgrade.yml
    - include_tasks: tasks/install-aur-helper.yml
    - include_tasks: tasks/install-packages.yml
    - include_tasks: tasks/install-flatpak-packages.yml
    - include_tasks: tasks/enable-fish-shell.yml
    - include_tasks: tasks/set-wallpaper.yml
  roles:
    - jetbrains-toolbox
      
