---
- name: Check if Flatpak is installed
  ansible.builtin.command: which flatpak
  register: flatpak_installed
  ignore_errors: true

- name: Print message if Flatpak is not installed
  ansible.builtin.debug:
    msg: "Flatpak is not installed, skipping Flatpak package installation."
  when: flatpak_installed.rc != 0

- name: Read Flatpak packages from YAML file
  slurp:
    src: "{{ playbook_dir }}/files/flatpak_packages.yml"
  register: flatpak_package_file
  when: flatpak_installed.rc == 0

- name: Parse Flatpak YAML content
  set_fact:
    flatpak_packages: "{{ flatpak_package_file.content | b64decode | from_yaml }}"
  when: flatpak_installed.rc == 0

- name: Combine Flatpak packages
  set_fact:
    combined_flatpak_packages: "{{ flatpak_packages.common + (flatpak_packages[effective_os_family] | default([])) }}"
  when: flatpak_installed.rc == 0

- name: Print Flatpak packages to be installed
  ansible.builtin.debug:
    msg: "Installing Flatpak packages: {{ combined_flatpak_packages }}"
  when: flatpak_installed.rc == 0 and combined_flatpak_packages | length > 0

- name: Install Flatpak packages
  flatpak:
    name: "{{ combined_flatpak_packages }}"
    state: present
  when: flatpak_installed.rc == 0 and combined_flatpak_packages | length > 0
