---
- name: Generate SSH config from Bitwarden Vault using bw CLI
  block:
    - name: Run Bitwarden CLI to get items from SSH folder
      command: bw list items --folderid 0aa03118-114c-4591-9f05-b2090089361b
      register: bw_output
      changed_when: false

    - name: Parse JSON output from bw command
      set_fact:
        ssh_items: "{{ bw_output.stdout | from_json }}"

    - name: debug
      ansible.builtin.debug:
        var: ssh_items

    - name: Ensure ~/.ssh directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.ssh"
        state: directory
        mode: '0700'
        
    - name: Create SSH config file based on Bitwarden items
      blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        block: |
          {% for item in ssh_items %}
          Host {{ item.fields | selectattr('name', 'equalto', 'host') | map(attribute='value') | first }}
              Hostname {{ item.login.uris[0].uri }}
              User {{ item.login.username }}
              IdentityFile ~/.ssh/{{ item.fields | selectattr('name', 'equalto', 'host') | map(attribute='value') | first }}
          {% endfor %}
        owner: "{{ lookup('env', 'USER') }}"
        mode: '0600'
        create: true
