# shellcheck shell=bash
# Synchronize Bitwarden SSH item metadata into OpenSSH configuration.
#
# Private keys remain in Bitwarden and are used through its desktop SSH
# agent. This script writes only public-key selector files and generated
# Host blocks. Add an `ssh_config` text custom field to an SSH item, using
# {{identity_file}} where its generated public-key path should appear.

set -euo pipefail
umask 077

decode_base64() {
  if base64 --decode </dev/null >/dev/null 2>&1; then
    base64 --decode
  else
    base64 -D
  fi
}

mode=manual
if [[ "$#" -gt 1 ]]; then
  echo "usage: bw-ssh-sync [--activation|--non-interactive]" >&2
  exit 2
fi
case "${1:-}" in
  "")
    ;;
  --activation)
    mode=activation
    ;;
  --non-interactive)
    mode=non-interactive
    ;;
  *)
    echo "usage: bw-ssh-sync [--activation|--non-interactive]" >&2
    exit 2
    ;;
esac

ssh_dir="${HOME}/.ssh"
public_dir="${ssh_dir}/bitwarden"
generated_config="${ssh_dir}/config.bitwarden"
manifest="${public_dir}/.manifest"

mkdir -p "$ssh_dir" "$public_dir"
chmod 700 "$ssh_dir" "$public_dir"

ensure_empty_config() {
  if [[ ! -e "$generated_config" ]]; then
    printf '%s\n' \
      '# Generated by bw-ssh-sync. Unlock Bitwarden and rerun to populate.' \
      >"$generated_config"
    chmod 600 "$generated_config"
  fi
}

status=$(bw status | jq -er '.status')
case "$status" in
  unlocked)
    ;;
  locked)
    if [[ "$mode" == non-interactive ]]; then
      ensure_empty_config
      echo "Bitwarden CLI is locked; skipped SSH metadata sync."
      exit 0
    fi
    export BW_SESSION
    BW_SESSION=$(bw unlock --raw)
    ;;
  unauthenticated)
    ensure_empty_config
    if [[ "$mode" == activation || "$mode" == non-interactive ]]; then
      echo "Bitwarden CLI is not logged in; skipped SSH metadata sync."
      echo "Run 'bw login' once, then rerun bw-ssh-sync." >&2
      exit 0
    fi
    echo "Bitwarden CLI is not logged in. Run 'bw login', then retry." >&2
    exit 1
    ;;
  *)
    echo "Unexpected Bitwarden CLI status: $status" >&2
    exit 1
    ;;
esac

bw sync >/dev/null
items=$(bw list items)
stage_dir=$(mktemp -d "${ssh_dir}/.bitwarden-sync.XXXXXX")
config_stage="${stage_dir}/config.bitwarden"
manifest_stage="${stage_dir}/manifest"

cleanup() {
  if [[ -d "$stage_dir" ]]; then
    find "$stage_dir" -type f -delete
    find "$stage_dir" -depth -type d -exec rmdir {} \; 2>/dev/null || true
  fi
}
trap cleanup EXIT

printf '%s\n\n' \
  '# Generated from Bitwarden SSH item metadata; do not edit.' \
  >"$config_stage"
: >"$manifest_stage"

key_count=0
configured_count=0

while IFS= read -r encoded_item; do
  [[ -n "$encoded_item" ]] || continue
  item=$(printf '%s' "$encoded_item" | decode_base64)
  id=$(printf '%s' "$item" | jq -r '.id')
  name=$(printf '%s' "$item" | jq -r '.name')
  public_key=$(printf '%s' "$item" | jq -r '.sshKey.publicKey // empty')
  expected_fingerprint=$(
    printf '%s' "$item" |
      jq -r '.sshKey.keyFingerprint // empty'
  )

  if [[ ! "$id" =~ ^[0-9a-fA-F-]+$ ]]; then
    echo "$name has an unsafe item ID; stopping." >&2
    exit 1
  fi
  if [[ -z "$public_key" || -z "$expected_fingerprint" ]]; then
    echo "$name has incomplete SSH key material; stopping." >&2
    exit 1
  fi

  actual_fingerprint=$(
    printf '%s\n' "$public_key" |
      ssh-keygen -E sha256 -lf - |
      awk '{ print $2 }'
  )
  if [[ "$actual_fingerprint" != "$expected_fingerprint" ]]; then
    echo "$name has a public-key fingerprint mismatch; stopping." >&2
    exit 1
  fi

  selector="${public_dir}/${id}.pub"
  printf '%s\n' "$public_key" >"${stage_dir}/${id}.pub"
  chmod 600 "${stage_dir}/${id}.pub"
  printf '%s\n' "$id" >>"$manifest_stage"
  key_count=$((key_count + 1))

  ssh_config=$(
    printf '%s' "$item" |
      jq -r '
        [.fields[]? | select(.name == "ssh_config") | .value][0] // empty
      '
  )
  if [[ -z "$ssh_config" ]]; then
    continue
  fi
  if [[ "$ssh_config" != *'{{identity_file}}'* ]]; then
    echo "$name has ssh_config metadata without {{identity_file}}; stopping." >&2
    exit 1
  fi

  rendered=$(
    SSH_CONFIG="$ssh_config" \
      IDENTITY_FILE="$selector" \
      jq -n -r '
        $ENV.SSH_CONFIG
        | gsub("\\{\\{identity_file\\}\\}"; $ENV.IDENTITY_FILE)
      '
  )
  printf '# Bitwarden: %s (%s)\n%s\n\n' "$name" "$id" "$rendered" \
    >>"$config_stage"
  configured_count=$((configured_count + 1))
done < <(
  printf '%s' "$items" |
    jq -r '.[] | select(.type == 5) | @base64'
)

ssh -G -F "$config_stage" __bitwarden_config_validation__ >/dev/null 2>&1
chmod 600 "$config_stage" "$manifest_stage"

while IFS= read -r id; do
  [[ -n "$id" ]] || continue
  mv "${stage_dir}/${id}.pub" "${public_dir}/${id}.pub"
done <"$manifest_stage"

if [[ -f "$manifest" ]]; then
  while IFS= read -r old_id; do
    [[ "$old_id" =~ ^[0-9a-fA-F-]+$ ]] || continue
    if ! grep -Fxq "$old_id" "$manifest_stage"; then
      stale_file="${public_dir}/${old_id}.pub"
      [[ ! -f "$stale_file" ]] || unlink "$stale_file"
    fi
  done <"$manifest"
fi

mv "$manifest_stage" "$manifest"
mv "$config_stage" "$generated_config"
chmod 600 "$manifest" "$generated_config"

echo "Synchronized $key_count Bitwarden public keys and $configured_count SSH config entries."
