---
- name: Install docker and docker-compose
  ansible.builtin.pacman:
    name:
      - docker
      - docker-compose
    state: present
  become: yes

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
    state: started
  become: yes