---
- name: Remove old Docker packages
  become: true
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - podman-docker
    - containerd
    - runc

- name: Install dependencies for Docker
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create directory for Docker GPG key
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker's official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    filename: docker

- name: Update apt cache after adding Docker repository
  become: true
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
    state: started
  become: true
