---
- name: Check if Starship is already installed
  command: which starship
  register: starship_check
  ignore_errors: true
  changed_when: false

- name: Download and install Starship prompt
  shell: |
    curl -sS https://starship.rs/install.sh -o /tmp/install_starship.sh
    sh /tmp/install_starship.sh -f -y
  when: starship_check.rc != 0
  args:
    creates: /usr/local/bin/starship
  become: true
